export const GET_REMINDERS = 'GET_REMINDERS';
export const ADD_REMINDER = 'ADD_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';

export const TOGGLE_FORM = 'TOGGLE_FORM';
export const TOGGLE_LIST = 'TOGGLE_LIST';
